# These are supported funding model platforms

github: [orielhaim]
#polar: orielhaim

# Uncomment and fill these if you configure them in the future:
# patreon: orielhaim
# open_collective: orielhaim
# ko_fi: orielhaim
# buy_me_a_coffee: orielhaim
# custom: []
