use crate::ir::PolicyDocument;

pub fn export_json(doc: &PolicyDocument) -> String {
    serde_json::to_string_pretty(doc).unwrap_or_else(|_| "{}".into())
}

pub fn export_yaml(doc: &PolicyDocument) -> String {
    yaml_serde::to_string(doc).unwrap_or_else(|_| String::new())
}

pub fn export_hcl(doc: &PolicyDocument) -> String {
    let mut out = String::new();

    for group in &doc.user_groups {
        out.push_str(&format!("user_group \"{}\" {{\n", group.name));
        if !group.members.is_empty() {
            out.push_str(&format!(
                "  members = {}\n",
                render_string_list(&group.members)
            ));
        }
        out.push_str("}\n\n");
    }

    for group in &doc.device_groups {
        out.push_str(&format!("device_group \"{}\" {{\n", group.name));
        if !group.endpoints.is_empty() {
            out.push_str(&format!(
                "  endpoints = {}\n",
                render_string_list(&group.endpoints)
            ));
        }
        out.push_str("}\n\n");
    }

    for tag in &doc.tags {
        out.push_str(&format!("tag \"{}\" {{\n", tag.name));
        if !tag.owners.is_empty() {
            out.push_str(&format!("  owners = {}\n", render_string_list(&tag.owners)));
        }
        out.push_str("}\n\n");
    }

    for acl in &doc.acls {
        out.push_str(&format!("acl \"{}\" {{\n", acl.name));
        out.push_str(&format!("  action   = \"{}\"\n", acl.action));
        out.push_str(&format!("  priority = {}\n", acl.priority));
        if !acl.src.is_empty() {
            out.push_str(&format!("  src      = {}\n", render_string_list(&acl.src)));
        }
        if !acl.dst.is_empty() {
            out.push_str(&format!("  dst      = {}\n", render_string_list(&acl.dst)));
        }
        if !acl.ports.is_empty() {
            out.push_str(&format!(
                "  ports    = {}\n",
                render_string_list(&acl.ports)
            ));
        }
        if let Some(proto) = &acl.protocol {
            out.push_str(&format!("  protocol = \"{proto}\"\n"));
        }
        if !acl.enabled {
            out.push_str("  enabled  = false\n");
        }
        out.push_str("}\n\n");
    }

    for test in &doc.tests {
        out.push_str(&format!("test \"{}\" {{\n", test.name));
        out.push_str(&format!("  src = \"{}\"\n", test.src));
        if !test.accept.is_empty() {
            out.push_str(&format!(
                "  accept = {}\n",
                render_string_list(&test.accept)
            ));
        }
        if !test.deny.is_empty() {
            out.push_str(&format!("  deny   = {}\n", render_string_list(&test.deny)));
        }
        out.push_str("}\n\n");
    }

    out
}

pub fn export_terraform(doc: &PolicyDocument) -> String {
    let mut out = String::from("# Generated by tunnet-policy-engine\n\n");

    for group in &doc.user_groups {
        out.push_str(&format!(
            r#"resource "tunnet_user_group" "{}" {{
  name = "{}"
}}

"#,
            tf_id(&group.name),
            group.name
        ));
    }

    for group in &doc.device_groups {
        out.push_str(&format!(
            r#"resource "tunnet_device_group" "{}" {{
  name = "{}"
}}

"#,
            tf_id(&group.name),
            group.name
        ));
    }

    for tag in &doc.tags {
        out.push_str(&format!(
            r#"resource "tunnet_tag" "{}" {{
  name = "{}"
}}

"#,
            tf_id(&tag.name),
            tag.name
        ));
    }

    for acl in &doc.acls {
        out.push_str(&format!(
            r#"resource "tunnet_acl_rule" "{}" {{
  name     = "{}"
  action   = "{}"
  priority = {}
}}

"#,
            tf_id(acl.key()),
            acl.name,
            acl.action,
            acl.priority
        ));
    }

    out
}

fn render_string_list(items: &[String]) -> String {
    let quoted: Vec<String> = items.iter().map(|s| format!("\"{s}\"")).collect();
    format!("[{}]", quoted.join(", "))
}

fn tf_id(name: &str) -> String {
    name.chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::hash::content_hash;
    use crate::ir::{AclRule, PolicyDocument, TagDefinition, UserGroup};
    use crate::parser::{Format, parse};

    #[test]
    fn yaml_round_trip_preserves_content_hash() {
        let doc = PolicyDocument {
            user_groups: vec![UserGroup {
                name: "eng".into(),
                members: vec!["a@x.com".into()],
            }],
            tags: vec![TagDefinition {
                name: "staging".into(),
                owners: vec![],
            }],
            acls: vec![AclRule {
                name: "allow-eng".into(),
                slug: None,
                action: "allow".into(),
                src: vec!["group:user:eng".into()],
                dst: vec!["tag:staging".into()],
                ports: vec!["443".into()],
                protocol: Some("tcp".into()),
                priority: 100,
                posture: vec![],
                labels: Default::default(),
                enabled: true,
            }],
            ..Default::default()
        };

        let yaml = export_yaml(&doc);
        let parsed = parse(Format::Yaml, &yaml).unwrap();
        assert_eq!(content_hash(&doc), content_hash(&parsed));
        assert_eq!(parsed.acls[0].name, "allow-eng");
        assert_eq!(parsed.user_groups[0].members, vec!["a@x.com".to_string()]);
    }
}
