import type {
  PolicyDiffResult,
  PolicySimulateResult,
  PolicyValidateResult,
} from "./types";

function formatValidationSection(result: PolicyValidateResult): string {
  const lines = ["## Validation"];

  if (result.valid) {
    lines.push("✅ Policy document is valid.");
  } else {
    lines.push("❌ Policy validation failed.");
    for (const error of result.errors ?? []) {
      const prefix = error.path ? `\`${error.path}\`: ` : "";
      lines.push(`- ${prefix}${error.message}`);
    }
  }

  for (const warning of result.warnings ?? []) {
    const prefix = warning.path ? `\`${warning.path}\`: ` : "";
    lines.push(`- ⚠️ ${prefix}${warning.message}`);
  }

  if (result.tests) {
    lines.push("");
    lines.push(
      `**Tests:** ${result.tests.passed} passed, ${result.tests.failed} failed`,
    );
    for (const test of result.tests.results ?? []) {
      const icon = test.passed ? "✅" : "❌";
      lines.push(
        `- ${icon} ${test.name}${test.message ? ` - ${test.message}` : ""}`,
      );
    }
  }

  return lines.join("\n");
}

function changeIcon(kind: "add" | "change" | "remove"): string {
  switch (kind) {
    case "add":
      return "➕";
    case "remove":
      return "➖";
    default:
      return "📝";
  }
}

function formatDiffSection(diff: PolicyDiffResult): string {
  const lines = ["## Semantic diff"];

  if (diff.changes.length === 0) {
    lines.push("No changes compared to live policy.");
    return lines.join("\n");
  }

  for (const change of diff.changes) {
    const summary = change.summary ? ` - ${change.summary}` : "";
    lines.push(
      `- ${changeIcon(change.kind)} **${change.kind}** \`${change.entity}/${change.name}\`${summary}`,
    );
  }

  if (diff.impact) {
    lines.push("");
    lines.push("### Impact");
    if (diff.impact.devicesAffected !== undefined) {
      lines.push(`- Devices affected: ${diff.impact.devicesAffected}`);
    }
    if (diff.impact.connectionsBroken !== undefined) {
      lines.push(
        `- Connections potentially broken: ${diff.impact.connectionsBroken}`,
      );
    }
  }

  return lines.join("\n");
}

function formatSimulationSection(simulation: PolicySimulateResult): string {
  const lines = ["## Simulation"];

  if (simulation.scenarios.length === 0) {
    lines.push("No scenarios were run.");
    return lines.join("\n");
  }

  lines.push("| Scenario | Verdict | Matched rules |");
  lines.push("| --- | --- | --- |");

  for (const scenario of simulation.scenarios) {
    const label =
      scenario.name ??
      `${scenario.src} → ${scenario.dst}${scenario.port ? `:${scenario.port}` : ""}`;
    const verdict = scenario.verdict === "allow" ? "✅ allow" : "❌ deny";
    const rules = scenario.matchedRules?.join(", ") ?? "-";
    lines.push(`| ${label} | ${verdict} | ${rules} |`);
  }

  return lines.join("\n");
}

export function formatPrComment(options: {
  policyLabel: string;
  validation: PolicyValidateResult;
  diff?: PolicyDiffResult;
  simulation?: PolicySimulateResult;
  applyMessage?: string;
}): string {
  const lines = [
    "## Tunnet policy check",
    "",
    `Policy path: \`${options.policyLabel}\``,
    "",
    formatValidationSection(options.validation),
  ];

  if (options.diff) {
    lines.push("");
    lines.push(formatDiffSection(options.diff));
  }

  if (options.simulation) {
    lines.push("");
    lines.push(formatSimulationSection(options.simulation));
  }

  if (options.applyMessage) {
    lines.push("");
    lines.push("## Apply");
    lines.push(options.applyMessage);
  }

  lines.push("");
  lines.push(
    "<sub>Generated by [tunnet-policy](https://github.com/tunnetio/Tunnet/tree/main/tools/gitops-policy-action)</sub>",
  );

  return lines.join("\n");
}
