{{- if .Values.credentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.credentials.secretName }}
  namespace: {{ include "tunnet-operator.namespace" . }}
  labels:
    {{- include "tunnet-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  api_key: {{ .Values.credentials.apiKey | quote }}
  org_id: {{ .Values.credentials.orgId | quote }}
  control_url: {{ .Values.credentials.controlUrl | quote }}
  management_url: {{ .Values.credentials.managementUrl | quote }}
{{- end }}
