/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AcceptInvitationInvitationIdRouteImport } from './routes/accept-invitation.$invitationId'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAccessRouteImport } from './routes/app/access'
import { Route as AppLogsRouteImport } from './routes/app/logs'
import { Route as AppOnboardingRouteImport } from './routes/app/onboarding'
import { Route as AppOrganizationRouteImport } from './routes/app/organization'
import { Route as AppRolesRouteImport } from './routes/app/roles'
import { Route as AppSettingsRouteRouteImport } from './routes/app/settings/route'
import { Route as AppTagsRouteImport } from './routes/app/tags'
import { Route as AppUsersRouteImport } from './routes/app/users'
import { Route as AuthSshRouteImport } from './routes/auth/ssh'
import { Route as DeviceIndexRouteImport } from './routes/device/index'
import { Route as DeviceApproveRouteImport } from './routes/device/approve'
import { Route as AppKubernetesIndexRouteImport } from './routes/app/kubernetes/index'
import { Route as AppMachinesIndexRouteImport } from './routes/app/machines/index'
import { Route as AppMachinesEndpointIdRouteImport } from './routes/app/machines/$endpointId'
import { Route as AppNetworksIndexRouteImport } from './routes/app/networks/index'
import { Route as AppNetworksNetworkIdRouteRouteImport } from './routes/app/networks/$networkId/route'
import { Route as AppPostureIndexRouteImport } from './routes/app/posture/index'
import { Route as AppPostureComplianceRouteImport } from './routes/app/posture/compliance'
import { Route as AppPostureIntegrationsRouteImport } from './routes/app/posture/integrations'
import { Route as AppRelaysIndexRouteImport } from './routes/app/relays/index'
import { Route as AppRelaysRelayIdRouteImport } from './routes/app/relays/$relayId'
import { Route as AppServesIndexRouteImport } from './routes/app/serves/index'
import { Route as AppServesServeIdRouteImport } from './routes/app/serves/$serveId'
import { Route as AppSettingsIndexRouteImport } from './routes/app/settings/index'
import { Route as AppSshSessionsIndexRouteImport } from './routes/app/ssh-sessions/index'
import { Route as AppTransfersIndexRouteImport } from './routes/app/transfers/index'
import { Route as AppTunnelsIndexRouteImport } from './routes/app/tunnels/index'
import { Route as AppTunnelsTunnelIdRouteImport } from './routes/app/tunnels/$tunnelId'
import { Route as AppKubernetesNetworksNetworkIdRouteImport } from './routes/app/kubernetes/networks/$networkId'
import { Route as AppNetworksNetworkIdIndexRouteImport } from './routes/app/networks/$networkId/index'
import { Route as AppNetworksNetworkIdAccessRouteImport } from './routes/app/networks/$networkId/access'
import { Route as AppNetworksNetworkIdEnrollmentRouteImport } from './routes/app/networks/$networkId/enrollment'
import { Route as AppNetworksNetworkIdMachinesRouteImport } from './routes/app/networks/$networkId/machines'
import { Route as AppNetworksNetworkIdMapRouteImport } from './routes/app/networks/$networkId/map'
import { Route as AppNetworksNetworkIdPolicyRouteImport } from './routes/app/networks/$networkId/policy'
import { Route as AppNetworksNetworkIdRoutesRouteImport } from './routes/app/networks/$networkId/routes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationInvitationIdRoute =
  AcceptInvitationInvitationIdRouteImport.update({
    id: '/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAccessRoute = AppAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLogsRoute = AppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrganizationRoute = AppOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRouteRoute = AppSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTagsRoute = AppTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthSshRoute = AuthSshRouteImport.update({
  id: '/auth/ssh',
  path: '/auth/ssh',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceIndexRoute = DeviceIndexRouteImport.update({
  id: '/device/',
  path: '/device/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceApproveRoute = DeviceApproveRouteImport.update({
  id: '/device/approve',
  path: '/device/approve',
  getParentRoute: () => rootRouteImport,
} as any)
const AppKubernetesIndexRoute = AppKubernetesIndexRouteImport.update({
  id: '/kubernetes/',
  path: '/kubernetes/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMachinesIndexRoute = AppMachinesIndexRouteImport.update({
  id: '/machines/',
  path: '/machines/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMachinesEndpointIdRoute = AppMachinesEndpointIdRouteImport.update({
  id: '/machines/$endpointId',
  path: '/machines/$endpointId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNetworksIndexRoute = AppNetworksIndexRouteImport.update({
  id: '/networks/',
  path: '/networks/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNetworksNetworkIdRouteRoute =
  AppNetworksNetworkIdRouteRouteImport.update({
    id: '/networks/$networkId',
    path: '/networks/$networkId',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppPostureIndexRoute = AppPostureIndexRouteImport.update({
  id: '/posture/',
  path: '/posture/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPostureComplianceRoute = AppPostureComplianceRouteImport.update({
  id: '/posture/compliance',
  path: '/posture/compliance',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPostureIntegrationsRoute = AppPostureIntegrationsRouteImport.update({
  id: '/posture/integrations',
  path: '/posture/integrations',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRelaysIndexRoute = AppRelaysIndexRouteImport.update({
  id: '/relays/',
  path: '/relays/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRelaysRelayIdRoute = AppRelaysRelayIdRouteImport.update({
  id: '/relays/$relayId',
  path: '/relays/$relayId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppServesIndexRoute = AppServesIndexRouteImport.update({
  id: '/serves/',
  path: '/serves/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppServesServeIdRoute = AppServesServeIdRouteImport.update({
  id: '/serves/$serveId',
  path: '/serves/$serveId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSshSessionsIndexRoute = AppSshSessionsIndexRouteImport.update({
  id: '/ssh-sessions/',
  path: '/ssh-sessions/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTransfersIndexRoute = AppTransfersIndexRouteImport.update({
  id: '/transfers/',
  path: '/transfers/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTunnelsIndexRoute = AppTunnelsIndexRouteImport.update({
  id: '/tunnels/',
  path: '/tunnels/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTunnelsTunnelIdRoute = AppTunnelsTunnelIdRouteImport.update({
  id: '/tunnels/$tunnelId',
  path: '/tunnels/$tunnelId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppKubernetesNetworksNetworkIdRoute =
  AppKubernetesNetworksNetworkIdRouteImport.update({
    id: '/kubernetes/networks/$networkId',
    path: '/kubernetes/networks/$networkId',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppNetworksNetworkIdIndexRoute =
  AppNetworksNetworkIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppNetworksNetworkIdRouteRoute,
  } as any)
const AppNetworksNetworkIdAccessRoute =
  AppNetworksNetworkIdAccessRouteImport.update({
    id: '/access',
    path: '/access',
    getParentRoute: () => AppNetworksNetworkIdRouteRoute,
  } as any)
const AppNetworksNetworkIdEnrollmentRoute =
  AppNetworksNetworkIdEnrollmentRouteImport.update({
    id: '/enrollment',
    path: '/enrollment',
    getParentRoute: () => AppNetworksNetworkIdRouteRoute,
  } as any)
const AppNetworksNetworkIdMachinesRoute =
  AppNetworksNetworkIdMachinesRouteImport.update({
    id: '/machines',
    path: '/machines',
    getParentRoute: () => AppNetworksNetworkIdRouteRoute,
  } as any)
const AppNetworksNetworkIdMapRoute = AppNetworksNetworkIdMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppNetworksNetworkIdRouteRoute,
} as any)
const AppNetworksNetworkIdPolicyRoute =
  AppNetworksNetworkIdPolicyRouteImport.update({
    id: '/policy',
    path: '/policy',
    getParentRoute: () => AppNetworksNetworkIdRouteRoute,
  } as any)
const AppNetworksNetworkIdRoutesRoute =
  AppNetworksNetworkIdRoutesRouteImport.update({
    id: '/routes',
    path: '/routes',
    getParentRoute: () => AppNetworksNetworkIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/consent': typeof ConsentRoute
  '/login': typeof LoginRoute
  '/app/settings': typeof AppSettingsRouteRouteWithChildren
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/app/access': typeof AppAccessRoute
  '/app/logs': typeof AppLogsRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/organization': typeof AppOrganizationRoute
  '/app/roles': typeof AppRolesRoute
  '/app/tags': typeof AppTagsRoute
  '/app/users': typeof AppUsersRoute
  '/auth/ssh': typeof AuthSshRoute
  '/device/approve': typeof DeviceApproveRoute
  '/app/': typeof AppIndexRoute
  '/device/': typeof DeviceIndexRoute
  '/app/networks/$networkId': typeof AppNetworksNetworkIdRouteRouteWithChildren
  '/app/machines/$endpointId': typeof AppMachinesEndpointIdRoute
  '/app/posture/compliance': typeof AppPostureComplianceRoute
  '/app/posture/integrations': typeof AppPostureIntegrationsRoute
  '/app/relays/$relayId': typeof AppRelaysRelayIdRoute
  '/app/serves/$serveId': typeof AppServesServeIdRoute
  '/app/tunnels/$tunnelId': typeof AppTunnelsTunnelIdRoute
  '/app/kubernetes/': typeof AppKubernetesIndexRoute
  '/app/machines/': typeof AppMachinesIndexRoute
  '/app/networks/': typeof AppNetworksIndexRoute
  '/app/posture/': typeof AppPostureIndexRoute
  '/app/relays/': typeof AppRelaysIndexRoute
  '/app/serves/': typeof AppServesIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/ssh-sessions/': typeof AppSshSessionsIndexRoute
  '/app/transfers/': typeof AppTransfersIndexRoute
  '/app/tunnels/': typeof AppTunnelsIndexRoute
  '/app/kubernetes/networks/$networkId': typeof AppKubernetesNetworksNetworkIdRoute
  '/app/networks/$networkId/access': typeof AppNetworksNetworkIdAccessRoute
  '/app/networks/$networkId/enrollment': typeof AppNetworksNetworkIdEnrollmentRoute
  '/app/networks/$networkId/machines': typeof AppNetworksNetworkIdMachinesRoute
  '/app/networks/$networkId/map': typeof AppNetworksNetworkIdMapRoute
  '/app/networks/$networkId/policy': typeof AppNetworksNetworkIdPolicyRoute
  '/app/networks/$networkId/routes': typeof AppNetworksNetworkIdRoutesRoute
  '/app/networks/$networkId/': typeof AppNetworksNetworkIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consent': typeof ConsentRoute
  '/login': typeof LoginRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/app/access': typeof AppAccessRoute
  '/app/logs': typeof AppLogsRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/organization': typeof AppOrganizationRoute
  '/app/roles': typeof AppRolesRoute
  '/app/tags': typeof AppTagsRoute
  '/app/users': typeof AppUsersRoute
  '/auth/ssh': typeof AuthSshRoute
  '/device/approve': typeof DeviceApproveRoute
  '/app': typeof AppIndexRoute
  '/device': typeof DeviceIndexRoute
  '/app/machines/$endpointId': typeof AppMachinesEndpointIdRoute
  '/app/posture/compliance': typeof AppPostureComplianceRoute
  '/app/posture/integrations': typeof AppPostureIntegrationsRoute
  '/app/relays/$relayId': typeof AppRelaysRelayIdRoute
  '/app/serves/$serveId': typeof AppServesServeIdRoute
  '/app/tunnels/$tunnelId': typeof AppTunnelsTunnelIdRoute
  '/app/kubernetes': typeof AppKubernetesIndexRoute
  '/app/machines': typeof AppMachinesIndexRoute
  '/app/networks': typeof AppNetworksIndexRoute
  '/app/posture': typeof AppPostureIndexRoute
  '/app/relays': typeof AppRelaysIndexRoute
  '/app/serves': typeof AppServesIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/app/ssh-sessions': typeof AppSshSessionsIndexRoute
  '/app/transfers': typeof AppTransfersIndexRoute
  '/app/tunnels': typeof AppTunnelsIndexRoute
  '/app/kubernetes/networks/$networkId': typeof AppKubernetesNetworksNetworkIdRoute
  '/app/networks/$networkId/access': typeof AppNetworksNetworkIdAccessRoute
  '/app/networks/$networkId/enrollment': typeof AppNetworksNetworkIdEnrollmentRoute
  '/app/networks/$networkId/machines': typeof AppNetworksNetworkIdMachinesRoute
  '/app/networks/$networkId/map': typeof AppNetworksNetworkIdMapRoute
  '/app/networks/$networkId/policy': typeof AppNetworksNetworkIdPolicyRoute
  '/app/networks/$networkId/routes': typeof AppNetworksNetworkIdRoutesRoute
  '/app/networks/$networkId': typeof AppNetworksNetworkIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/consent': typeof ConsentRoute
  '/login': typeof LoginRoute
  '/app/settings': typeof AppSettingsRouteRouteWithChildren
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/app/access': typeof AppAccessRoute
  '/app/logs': typeof AppLogsRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/organization': typeof AppOrganizationRoute
  '/app/roles': typeof AppRolesRoute
  '/app/tags': typeof AppTagsRoute
  '/app/users': typeof AppUsersRoute
  '/auth/ssh': typeof AuthSshRoute
  '/device/approve': typeof DeviceApproveRoute
  '/app/': typeof AppIndexRoute
  '/device/': typeof DeviceIndexRoute
  '/app/networks/$networkId': typeof AppNetworksNetworkIdRouteRouteWithChildren
  '/app/machines/$endpointId': typeof AppMachinesEndpointIdRoute
  '/app/posture/compliance': typeof AppPostureComplianceRoute
  '/app/posture/integrations': typeof AppPostureIntegrationsRoute
  '/app/relays/$relayId': typeof AppRelaysRelayIdRoute
  '/app/serves/$serveId': typeof AppServesServeIdRoute
  '/app/tunnels/$tunnelId': typeof AppTunnelsTunnelIdRoute
  '/app/kubernetes/': typeof AppKubernetesIndexRoute
  '/app/machines/': typeof AppMachinesIndexRoute
  '/app/networks/': typeof AppNetworksIndexRoute
  '/app/posture/': typeof AppPostureIndexRoute
  '/app/relays/': typeof AppRelaysIndexRoute
  '/app/serves/': typeof AppServesIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/ssh-sessions/': typeof AppSshSessionsIndexRoute
  '/app/transfers/': typeof AppTransfersIndexRoute
  '/app/tunnels/': typeof AppTunnelsIndexRoute
  '/app/kubernetes/networks/$networkId': typeof AppKubernetesNetworksNetworkIdRoute
  '/app/networks/$networkId/access': typeof AppNetworksNetworkIdAccessRoute
  '/app/networks/$networkId/enrollment': typeof AppNetworksNetworkIdEnrollmentRoute
  '/app/networks/$networkId/machines': typeof AppNetworksNetworkIdMachinesRoute
  '/app/networks/$networkId/map': typeof AppNetworksNetworkIdMapRoute
  '/app/networks/$networkId/policy': typeof AppNetworksNetworkIdPolicyRoute
  '/app/networks/$networkId/routes': typeof AppNetworksNetworkIdRoutesRoute
  '/app/networks/$networkId/': typeof AppNetworksNetworkIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/consent'
    | '/login'
    | '/app/settings'
    | '/accept-invitation/$invitationId'
    | '/app/access'
    | '/app/logs'
    | '/app/onboarding'
    | '/app/organization'
    | '/app/roles'
    | '/app/tags'
    | '/app/users'
    | '/auth/ssh'
    | '/device/approve'
    | '/app/'
    | '/device/'
    | '/app/networks/$networkId'
    | '/app/machines/$endpointId'
    | '/app/posture/compliance'
    | '/app/posture/integrations'
    | '/app/relays/$relayId'
    | '/app/serves/$serveId'
    | '/app/tunnels/$tunnelId'
    | '/app/kubernetes/'
    | '/app/machines/'
    | '/app/networks/'
    | '/app/posture/'
    | '/app/relays/'
    | '/app/serves/'
    | '/app/settings/'
    | '/app/ssh-sessions/'
    | '/app/transfers/'
    | '/app/tunnels/'
    | '/app/kubernetes/networks/$networkId'
    | '/app/networks/$networkId/access'
    | '/app/networks/$networkId/enrollment'
    | '/app/networks/$networkId/machines'
    | '/app/networks/$networkId/map'
    | '/app/networks/$networkId/policy'
    | '/app/networks/$networkId/routes'
    | '/app/networks/$networkId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/consent'
    | '/login'
    | '/accept-invitation/$invitationId'
    | '/app/access'
    | '/app/logs'
    | '/app/onboarding'
    | '/app/organization'
    | '/app/roles'
    | '/app/tags'
    | '/app/users'
    | '/auth/ssh'
    | '/device/approve'
    | '/app'
    | '/device'
    | '/app/machines/$endpointId'
    | '/app/posture/compliance'
    | '/app/posture/integrations'
    | '/app/relays/$relayId'
    | '/app/serves/$serveId'
    | '/app/tunnels/$tunnelId'
    | '/app/kubernetes'
    | '/app/machines'
    | '/app/networks'
    | '/app/posture'
    | '/app/relays'
    | '/app/serves'
    | '/app/settings'
    | '/app/ssh-sessions'
    | '/app/transfers'
    | '/app/tunnels'
    | '/app/kubernetes/networks/$networkId'
    | '/app/networks/$networkId/access'
    | '/app/networks/$networkId/enrollment'
    | '/app/networks/$networkId/machines'
    | '/app/networks/$networkId/map'
    | '/app/networks/$networkId/policy'
    | '/app/networks/$networkId/routes'
    | '/app/networks/$networkId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/consent'
    | '/login'
    | '/app/settings'
    | '/accept-invitation/$invitationId'
    | '/app/access'
    | '/app/logs'
    | '/app/onboarding'
    | '/app/organization'
    | '/app/roles'
    | '/app/tags'
    | '/app/users'
    | '/auth/ssh'
    | '/device/approve'
    | '/app/'
    | '/device/'
    | '/app/networks/$networkId'
    | '/app/machines/$endpointId'
    | '/app/posture/compliance'
    | '/app/posture/integrations'
    | '/app/relays/$relayId'
    | '/app/serves/$serveId'
    | '/app/tunnels/$tunnelId'
    | '/app/kubernetes/'
    | '/app/machines/'
    | '/app/networks/'
    | '/app/posture/'
    | '/app/relays/'
    | '/app/serves/'
    | '/app/settings/'
    | '/app/ssh-sessions/'
    | '/app/transfers/'
    | '/app/tunnels/'
    | '/app/kubernetes/networks/$networkId'
    | '/app/networks/$networkId/access'
    | '/app/networks/$networkId/enrollment'
    | '/app/networks/$networkId/machines'
    | '/app/networks/$networkId/map'
    | '/app/networks/$networkId/policy'
    | '/app/networks/$networkId/routes'
    | '/app/networks/$networkId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ConsentRoute: typeof ConsentRoute
  LoginRoute: typeof LoginRoute
  AcceptInvitationInvitationIdRoute: typeof AcceptInvitationInvitationIdRoute
  AuthSshRoute: typeof AuthSshRoute
  DeviceApproveRoute: typeof DeviceApproveRoute
  DeviceIndexRoute: typeof DeviceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation/$invitationId': {
      id: '/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId'
      preLoaderRoute: typeof AcceptInvitationInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/access': {
      id: '/app/access'
      path: '/access'
      fullPath: '/app/access'
      preLoaderRoute: typeof AppAccessRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/logs': {
      id: '/app/logs'
      path: '/logs'
      fullPath: '/app/logs'
      preLoaderRoute: typeof AppLogsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/organization': {
      id: '/app/organization'
      path: '/organization'
      fullPath: '/app/organization'
      preLoaderRoute: typeof AppOrganizationRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/roles': {
      id: '/app/roles'
      path: '/roles'
      fullPath: '/app/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/tags': {
      id: '/app/tags'
      path: '/tags'
      fullPath: '/app/tags'
      preLoaderRoute: typeof AppTagsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/auth/ssh': {
      id: '/auth/ssh'
      path: '/auth/ssh'
      fullPath: '/auth/ssh'
      preLoaderRoute: typeof AuthSshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device/': {
      id: '/device/'
      path: '/device'
      fullPath: '/device/'
      preLoaderRoute: typeof DeviceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device/approve': {
      id: '/device/approve'
      path: '/device/approve'
      fullPath: '/device/approve'
      preLoaderRoute: typeof DeviceApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/kubernetes/': {
      id: '/app/kubernetes/'
      path: '/kubernetes'
      fullPath: '/app/kubernetes/'
      preLoaderRoute: typeof AppKubernetesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/machines/': {
      id: '/app/machines/'
      path: '/machines'
      fullPath: '/app/machines/'
      preLoaderRoute: typeof AppMachinesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/machines/$endpointId': {
      id: '/app/machines/$endpointId'
      path: '/machines/$endpointId'
      fullPath: '/app/machines/$endpointId'
      preLoaderRoute: typeof AppMachinesEndpointIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/networks/': {
      id: '/app/networks/'
      path: '/networks'
      fullPath: '/app/networks/'
      preLoaderRoute: typeof AppNetworksIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/networks/$networkId': {
      id: '/app/networks/$networkId'
      path: '/networks/$networkId'
      fullPath: '/app/networks/$networkId'
      preLoaderRoute: typeof AppNetworksNetworkIdRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/posture/': {
      id: '/app/posture/'
      path: '/posture'
      fullPath: '/app/posture/'
      preLoaderRoute: typeof AppPostureIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/posture/compliance': {
      id: '/app/posture/compliance'
      path: '/posture/compliance'
      fullPath: '/app/posture/compliance'
      preLoaderRoute: typeof AppPostureComplianceRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/posture/integrations': {
      id: '/app/posture/integrations'
      path: '/posture/integrations'
      fullPath: '/app/posture/integrations'
      preLoaderRoute: typeof AppPostureIntegrationsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/relays/': {
      id: '/app/relays/'
      path: '/relays'
      fullPath: '/app/relays/'
      preLoaderRoute: typeof AppRelaysIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/relays/$relayId': {
      id: '/app/relays/$relayId'
      path: '/relays/$relayId'
      fullPath: '/app/relays/$relayId'
      preLoaderRoute: typeof AppRelaysRelayIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/serves/': {
      id: '/app/serves/'
      path: '/serves'
      fullPath: '/app/serves/'
      preLoaderRoute: typeof AppServesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/serves/$serveId': {
      id: '/app/serves/$serveId'
      path: '/serves/$serveId'
      fullPath: '/app/serves/$serveId'
      preLoaderRoute: typeof AppServesServeIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/app/ssh-sessions/': {
      id: '/app/ssh-sessions/'
      path: '/ssh-sessions'
      fullPath: '/app/ssh-sessions/'
      preLoaderRoute: typeof AppSshSessionsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/transfers/': {
      id: '/app/transfers/'
      path: '/transfers'
      fullPath: '/app/transfers/'
      preLoaderRoute: typeof AppTransfersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/tunnels/': {
      id: '/app/tunnels/'
      path: '/tunnels'
      fullPath: '/app/tunnels/'
      preLoaderRoute: typeof AppTunnelsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/tunnels/$tunnelId': {
      id: '/app/tunnels/$tunnelId'
      path: '/tunnels/$tunnelId'
      fullPath: '/app/tunnels/$tunnelId'
      preLoaderRoute: typeof AppTunnelsTunnelIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/kubernetes/networks/$networkId': {
      id: '/app/kubernetes/networks/$networkId'
      path: '/kubernetes/networks/$networkId'
      fullPath: '/app/kubernetes/networks/$networkId'
      preLoaderRoute: typeof AppKubernetesNetworksNetworkIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/networks/$networkId/': {
      id: '/app/networks/$networkId/'
      path: '/'
      fullPath: '/app/networks/$networkId/'
      preLoaderRoute: typeof AppNetworksNetworkIdIndexRouteImport
      parentRoute: typeof AppNetworksNetworkIdRouteRoute
    }
    '/app/networks/$networkId/access': {
      id: '/app/networks/$networkId/access'
      path: '/access'
      fullPath: '/app/networks/$networkId/access'
      preLoaderRoute: typeof AppNetworksNetworkIdAccessRouteImport
      parentRoute: typeof AppNetworksNetworkIdRouteRoute
    }
    '/app/networks/$networkId/enrollment': {
      id: '/app/networks/$networkId/enrollment'
      path: '/enrollment'
      fullPath: '/app/networks/$networkId/enrollment'
      preLoaderRoute: typeof AppNetworksNetworkIdEnrollmentRouteImport
      parentRoute: typeof AppNetworksNetworkIdRouteRoute
    }
    '/app/networks/$networkId/machines': {
      id: '/app/networks/$networkId/machines'
      path: '/machines'
      fullPath: '/app/networks/$networkId/machines'
      preLoaderRoute: typeof AppNetworksNetworkIdMachinesRouteImport
      parentRoute: typeof AppNetworksNetworkIdRouteRoute
    }
    '/app/networks/$networkId/map': {
      id: '/app/networks/$networkId/map'
      path: '/map'
      fullPath: '/app/networks/$networkId/map'
      preLoaderRoute: typeof AppNetworksNetworkIdMapRouteImport
      parentRoute: typeof AppNetworksNetworkIdRouteRoute
    }
    '/app/networks/$networkId/policy': {
      id: '/app/networks/$networkId/policy'
      path: '/policy'
      fullPath: '/app/networks/$networkId/policy'
      preLoaderRoute: typeof AppNetworksNetworkIdPolicyRouteImport
      parentRoute: typeof AppNetworksNetworkIdRouteRoute
    }
    '/app/networks/$networkId/routes': {
      id: '/app/networks/$networkId/routes'
      path: '/routes'
      fullPath: '/app/networks/$networkId/routes'
      preLoaderRoute: typeof AppNetworksNetworkIdRoutesRouteImport
      parentRoute: typeof AppNetworksNetworkIdRouteRoute
    }
  }
}

interface AppSettingsRouteRouteChildren {
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteRouteChildren: AppSettingsRouteRouteChildren = {
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteRouteWithChildren =
  AppSettingsRouteRoute._addFileChildren(AppSettingsRouteRouteChildren)

interface AppNetworksNetworkIdRouteRouteChildren {
  AppNetworksNetworkIdAccessRoute: typeof AppNetworksNetworkIdAccessRoute
  AppNetworksNetworkIdEnrollmentRoute: typeof AppNetworksNetworkIdEnrollmentRoute
  AppNetworksNetworkIdMachinesRoute: typeof AppNetworksNetworkIdMachinesRoute
  AppNetworksNetworkIdMapRoute: typeof AppNetworksNetworkIdMapRoute
  AppNetworksNetworkIdPolicyRoute: typeof AppNetworksNetworkIdPolicyRoute
  AppNetworksNetworkIdRoutesRoute: typeof AppNetworksNetworkIdRoutesRoute
  AppNetworksNetworkIdIndexRoute: typeof AppNetworksNetworkIdIndexRoute
}

const AppNetworksNetworkIdRouteRouteChildren: AppNetworksNetworkIdRouteRouteChildren =
  {
    AppNetworksNetworkIdAccessRoute: AppNetworksNetworkIdAccessRoute,
    AppNetworksNetworkIdEnrollmentRoute: AppNetworksNetworkIdEnrollmentRoute,
    AppNetworksNetworkIdMachinesRoute: AppNetworksNetworkIdMachinesRoute,
    AppNetworksNetworkIdMapRoute: AppNetworksNetworkIdMapRoute,
    AppNetworksNetworkIdPolicyRoute: AppNetworksNetworkIdPolicyRoute,
    AppNetworksNetworkIdRoutesRoute: AppNetworksNetworkIdRoutesRoute,
    AppNetworksNetworkIdIndexRoute: AppNetworksNetworkIdIndexRoute,
  }

const AppNetworksNetworkIdRouteRouteWithChildren =
  AppNetworksNetworkIdRouteRoute._addFileChildren(
    AppNetworksNetworkIdRouteRouteChildren,
  )

interface AppRouteRouteChildren {
  AppSettingsRouteRoute: typeof AppSettingsRouteRouteWithChildren
  AppAccessRoute: typeof AppAccessRoute
  AppLogsRoute: typeof AppLogsRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppOrganizationRoute: typeof AppOrganizationRoute
  AppRolesRoute: typeof AppRolesRoute
  AppTagsRoute: typeof AppTagsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppNetworksNetworkIdRouteRoute: typeof AppNetworksNetworkIdRouteRouteWithChildren
  AppMachinesEndpointIdRoute: typeof AppMachinesEndpointIdRoute
  AppPostureComplianceRoute: typeof AppPostureComplianceRoute
  AppPostureIntegrationsRoute: typeof AppPostureIntegrationsRoute
  AppRelaysRelayIdRoute: typeof AppRelaysRelayIdRoute
  AppServesServeIdRoute: typeof AppServesServeIdRoute
  AppTunnelsTunnelIdRoute: typeof AppTunnelsTunnelIdRoute
  AppKubernetesIndexRoute: typeof AppKubernetesIndexRoute
  AppMachinesIndexRoute: typeof AppMachinesIndexRoute
  AppNetworksIndexRoute: typeof AppNetworksIndexRoute
  AppPostureIndexRoute: typeof AppPostureIndexRoute
  AppRelaysIndexRoute: typeof AppRelaysIndexRoute
  AppServesIndexRoute: typeof AppServesIndexRoute
  AppSshSessionsIndexRoute: typeof AppSshSessionsIndexRoute
  AppTransfersIndexRoute: typeof AppTransfersIndexRoute
  AppTunnelsIndexRoute: typeof AppTunnelsIndexRoute
  AppKubernetesNetworksNetworkIdRoute: typeof AppKubernetesNetworksNetworkIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppSettingsRouteRoute: AppSettingsRouteRouteWithChildren,
  AppAccessRoute: AppAccessRoute,
  AppLogsRoute: AppLogsRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppOrganizationRoute: AppOrganizationRoute,
  AppRolesRoute: AppRolesRoute,
  AppTagsRoute: AppTagsRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
  AppNetworksNetworkIdRouteRoute: AppNetworksNetworkIdRouteRouteWithChildren,
  AppMachinesEndpointIdRoute: AppMachinesEndpointIdRoute,
  AppPostureComplianceRoute: AppPostureComplianceRoute,
  AppPostureIntegrationsRoute: AppPostureIntegrationsRoute,
  AppRelaysRelayIdRoute: AppRelaysRelayIdRoute,
  AppServesServeIdRoute: AppServesServeIdRoute,
  AppTunnelsTunnelIdRoute: AppTunnelsTunnelIdRoute,
  AppKubernetesIndexRoute: AppKubernetesIndexRoute,
  AppMachinesIndexRoute: AppMachinesIndexRoute,
  AppNetworksIndexRoute: AppNetworksIndexRoute,
  AppPostureIndexRoute: AppPostureIndexRoute,
  AppRelaysIndexRoute: AppRelaysIndexRoute,
  AppServesIndexRoute: AppServesIndexRoute,
  AppSshSessionsIndexRoute: AppSshSessionsIndexRoute,
  AppTransfersIndexRoute: AppTransfersIndexRoute,
  AppTunnelsIndexRoute: AppTunnelsIndexRoute,
  AppKubernetesNetworksNetworkIdRoute: AppKubernetesNetworksNetworkIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  ConsentRoute: ConsentRoute,
  LoginRoute: LoginRoute,
  AcceptInvitationInvitationIdRoute: AcceptInvitationInvitationIdRoute,
  AuthSshRoute: AuthSshRoute,
  DeviceApproveRoute: DeviceApproveRoute,
  DeviceIndexRoute: DeviceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
