/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * A handle to the local overlay. Depending on whether this process won the
 * coordinator race, this is either a full coordinator (owning the iroh
 * endpoint) or a lightweight client relaying via UDS.
 */
export declare class TunnetNode {
  /** Create (or connect to) a local overlay node. */
  static create(cfg: NodeConfig): Promise<TunnetNode>;
  /** Our own endpoint id (hex). */
  endpointId(): string;
  /** Are we currently acting as the coordinator for this machine? */
  isCoordinator(): boolean;
  /** List peers currently known to the routing table. */
  listPeers(): Promise<Array<PeerJs>>;
  /**
   * Open a duplex stream to `host:port` where `host` is a peer overlay IP,
   * hostname, or endpoint id.
   */
  openStream(host: string, port: number): Promise<TunnetStream>;
  /** Best-effort shutdown. Multiple calls are safe. */
  close(): Promise<void>;
  /** Send a local file or directory to a mesh peer. */
  sendFile(
    path: string,
    target: string,
    message?: string | undefined | null,
  ): Promise<Array<TransferJs>>;
  /** Accept a pending inbound transfer offer. */
  acceptTransfer(transferId: string): Promise<TransferJs>;
  /** Reject a pending inbound transfer offer. */
  rejectTransfer(
    transferId: string,
    reason?: string | undefined | null,
  ): Promise<void>;
  /** List pending inbound offers (prompt consent mode). */
  listPendingTransfers(): Promise<Array<TransferJs>>;
  /** List active transfers. */
  listTransfers(): Promise<Array<TransferJs>>;
}

/** A duplex byte stream. Read via `read()`, write via `write()`, close via `close()`. */
export declare class TunnetStream {
  /** Read up to `max_len` bytes. Returns an empty buffer at EOF. */
  read(maxLen: number): Promise<Buffer>;
  /** Write all `data` bytes. */
  write(data: Buffer): Promise<void>;
  end(): Promise<void>;
}

/**
 * One-shot enrolment. Persists identity+state to `state_dir` so subsequent
 * `TunnetNode.create()` calls can bootstrap without a token.
 */
export declare function enroll(cfg: EnrollConfig): Promise<EnrollResult>;

export interface EnrollConfig {
  controlUrl: string;
  /** One-time enrollment token (agent-style enrolment). */
  token?: string;
  /** Management API base URL for API-key SDK enrolment. */
  managementUrl?: string;
  apiKey?: string;
  organizationId?: string;
  networkId?: string;
  hostname?: string;
  stateDir?: string;
  processName?: string;
  runtime?: string;
}

export interface EnrollResult {
  endpointId: string;
  ip: string;
  network: string;
}

export interface NodeConfig {
  /**
   * Path to the state directory (identity + persisted state).
   * If not provided we use `TUNNET_STATE_DIR`, `XDG_STATE_HOME`, etc.
   */
  stateDir?: string;
  hostname?: string;
  pollSecs?: number;
  /**
   * When true, avoids the coordinator dance and always creates a private
   * endpoint for this process. Useful in tests or single-process scenarios.
   */
  standalone?: boolean;
  /** Control plane URL used after enrolment. */
  controlUrl?: string;
  /** Auto-enrol via API key when no persisted identity exists. */
  managementUrl?: string;
  apiKey?: string;
  organizationId?: string;
  networkId?: string;
  processName?: string;
  runtime?: string;
}

export interface PeerJs {
  ip: string;
  hostname: string;
  endpointId: string;
  tags: Array<string>;
}

export interface TransferJs {
  transferId: string;
  direction: string;
  peerEndpointId: string;
  peerHostname?: string;
  fileName: string;
  size: number;
  hash: string;
  status: string;
  percent: number;
  bytesTransferred: number;
  message?: string;
  error?: string;
  inboxPath?: string;
  isDirectory: boolean;
}
